name: "Pull Request Labeler"
on: [push]
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/git-client-plugin/git-client-plugin/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_triage_uses-labeler_9
    - run: rm starting_triage_uses-labeler_9
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1676581928-c797686'
        target-directory: 'git-client-plugin/.github/workflows/labeler/triage'
      continue-on-error: true
    - name: Check push directory exit code
      if: steps.push_directory.outcome == 'failure'
      run: |
        echo 'push failed, trying pull and then push'
        git fetch
        git merge --abort origin/1676581928-c797686
        while ! git push origin {time}; do
          git fetch
          git merge --abort origin/1676581928-c797686
        done
